### ISSUE TITLE
Compare results output

### ISSUE THREAD

**Issue by RasheedAZ** [Merrit/unit_bargain_hunter#72]
I just noticed the amount of information the compare results outputs makes it harder to read in 1-2 seconds. It's giving `$/mg, $/g, $/kg, $/oz, $/lb`

Would be great if in the settings somewhere the user could restrict these to just one or two. 

Also, outputting $/weight for mg, g and kg may not be necessary as most people would be a able to do that mentally by just shifting zeros...

**Comment by Merrit** [comment]
I'm not sure how a preference for this would look without being rather verbose.. :thinking: 

> Also, outputting $/weight for mg, g and kg may not be necessary as most people would be a able to do that mentally by just shifting zeros...

I personally know multiple people who can't do this easily in their head and appreciate having them readily visible.

Do you have any specific suggestions on what a setting for this would look like? I will have to give it some thought.

**Comment by RasheedAZ** [comment]
> Do you have any specific suggestions on what a setting for this would look like? I will have to give it some thought.

Perhaps have a setting for this in options where the user can select the unit(s) they'd like to be displayed...?

**Comment by Merrit** [comment]
Right, I have something of an idea in mind, I will play around with it a bit. :)

**Comment by Merrit** [comment]
Here is what I've come up with..

Before:

![image](https://github.com/Merrit/unit_bargain_hunter/assets/9575627/dfb1d724-70d0-44b3-83c3-2c404fab4103)

Settings:

![image](https://github.com/Merrit/unit_bargain_hunter/assets/9575627/0f7af234-ee40-4b12-85b7-47b74c05f065)

After:

![image](https://github.com/Merrit/unit_bargain_hunter/assets/9575627/539226fc-65d4-42ef-9c2f-7a005683c835)

**Comment by RasheedAZ** [comment]
This is great, thanks. Only other thing I can think of to improve is to display symbols abbreviations instead of full units. For example, `$4.49/kg` instead of `$4.49 per kilogramme`. 

It's already doing that with the currency: `$4.49` instead of `four dollars and forty-nine cents` so perhaps the same with the weight...?
