### ISSUE TITLE
Feedback: Need new units!

### ISSUE THREAD

**Issue by COALROCK8642** [Merrit/unit_bargain_hunter#80]
1. ; a dozen (12 items), half-dozen (6 items), a box (20-30-40 items (do make all of these)), custom unit possibility

Try to include standardisation by being top result as user chooses his value, also implement favourite to pin on top. (I'm not UI and GUI person, you have to make it look convienent.)

2. Need standardisation of results; like putting oz but getting in $/gram, since I already choose MKS

3. Need, sub unit compare, with custom formula; imagine me getting slightly more (about 5%) $/gram but second attribute is like way better (about 20%) so also you show results on what basis you compate

4. (extending 1.) ability to put custom units

5. (extending 3.) ability to put custom formula for normalisation, can be average or exponential

6. (extending 5.) Last, ability to make complex formula on each and everything and default to normalised average

Your apps not best; but is capable for dailies and locals who keep finding ways to comprehensively compare, hope you can make click and touch easy
Also extend for people who maintain stats sheet, they like to buy in both ups and downs but sell product at decent above the average to make sales.
Like, 200 items at 105% and 100 at 95% average is 101.67%; but they display at shop at 102% all times to make sales.

Good Luck!

**Comment by Merrit** [comment]
Hi there, thanks for the feedback!

> 1. ; a dozen (12 items), half-dozen (6 items), a box (20-30-40 items (do make all of these)), custom unit possibility

This can be accomplished simply by setting the number of items, for example a dozen:

![image](https://github.com/Merrit/unit_bargain_hunter/assets/9575627/c603cdb0-a641-43dd-b50b-2f6919cebff9)

> implement favourite to pin on top

Pin the sheet, or pin an item?

![image](https://github.com/Merrit/unit_bargain_hunter/assets/9575627/6fd365bb-2cad-4ef2-a766-bd1cf78ec661)

> 2\. Need standardisation of results; like putting oz but getting in $/gram, since I already choose MKS

The results show all units a product can be converted to, as it can be easier to compare in a different unit at a glance. Eg `$0.009/mg - $0.005/mg` vs `$8646.667/kg - $5495.00/kg` -- in this instance it is more obvious with the kg comparison which one is cheaper, and by how large a factor.

---

Your other points I am afraid I don't quite understand, can you elaborate or rephrase?
